### ISSUE TITLE
Promise: Missing PM's profile photo

### ISSUE THREAD

**Issue by itwasup** [wevisdemo/parliament-watch#130] opened 2024-10-18 07:12 UTC
**Describe the bug**
The profile photo of PM is missing

**To Reproduce**
1. Go to https://promise-main.parliament-watch.pages.dev/promises

**Expected behavior**
The photo of the PM should be displayed

**Screenshots**
![image](https://github.com/user-attachments/assets/01fbf009-8f23-4373-87c5-bf57117110df)

**Comment by Th1nkK1D** [comment] 2024-10-18 08:12
So far as I check, there are 2 related issues.

1. Look like the current code didn't use `avatar` from politicians' data. Even though the image is actually missing, corrected placeholder image is provided as the `avatar` value like in [her profile page](https://promise-main.parliament-watch.pages.dev/politicians/%E0%B9%81%E0%B8%9E%E0%B8%A3%E0%B8%97%E0%B8%AD%E0%B8%87%E0%B8%98%E0%B8%B2%E0%B8%A3-%E0%B8%8A%E0%B8%B4%E0%B8%99%E0%B8%A7%E0%B8%B1%E0%B8%95%E0%B8%A3): 
![image](https://github.com/user-attachments/assets/e786a18b-25d6-4d45-a681-d41777dceae3) This one should be fixed from the code side. So this issue can be picked up.
2. Her picture is actually [here](https://promise-main.parliament-watch.pages.dev/images/politicians/%E0%B9%81%E0%B8%9E%E0%B8%97%E0%B8%AD%E0%B8%87%E0%B8%98%E0%B8%B2%E0%B8%A3-%E0%B8%8A%E0%B8%B4%E0%B8%99%E0%B8%A7%E0%B8%B1%E0%B8%95%E0%B8%A3.webp). The problem is her name in [Politicians sheets](https://docs.google.com/spreadsheets/d/1SbX2kgAGsslbhGuB-EI_YdSAnIt3reU1_OEtWmDVOVk/edit?pli=1&gid=2072868880#gid=2072868880) are `แพรทองธาร ชินวัตร` but the picture image is `แพทองธาร-ชินวัตร.webp` one of her first name is incorrect. @itwasup  If the sheets is incorrect, we need to find and replace all of the sheets, and there is no need to change the code.

**Comment by Th1nkK1D** [comment] 2024-10-18 08:17
## Notes for contributor
- This issue is based on the unreleased promise feature. Checkout and create PR on `promise/main` branch.
- The entry source code file: `src/routes/promises/+page.svelte` for the page UI and `src/routes/promises/+page.server.ts` for the data preparation.

**Comment by itwasup** [comment] 2024-10-21 09:44
@Th1nkK1D I've updated her name in the sheet 'Politicians'. I modified only the "firstname" column, and it automatically updated the corresponding ID.

**Closed** 2024-10-22 15:55 UTC
Labels: bug
